### ISSUE TITLE
ssh module

### ISSUE THREAD

**Issue by bowtiedbearz** [bearz-io/js#12]
create a port of [ssh2](https://github.com/mscdex/ssh2) that is friendlier to using deno and web friendly APIs.  

- [ ] use typescript
- [ ] use test suite (deno, vite)
- [ ] use Uint8Array over Buffer
- [ ] do not depend on node-gyp
- [ ] do not depend on cpu-features
